### ISSUE TITLE
Replace to getSharedPreferences

### ISSUE THREAD

**Issue by devdszerszen** [kaemo/FirstAndroidProject#5]
https://github.com/kaemo/FirstAndroidProject/blob/f2b8b6f99c561b19acf08f2d43e6b09e2e3dc00f/app/src/main/java/com/example/myfirstandroidapp/MainActivity.kt#L34

- Create global SHARED_PREFS_KEY in companion object
- use getSharedPreferences method with created key instead of getPreferences
- create lateinit var with sharedPreferences in MainActivity to avoid multiple initialization

**Comment by kaemo** [comment]
done in commit d61e3e38142f1563a7feb25d22c6891f28398767
